import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn, Roboto, Playpen_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { getCurrentUser } from "@/lib/auth";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const playpen = Playpen_Sans_Arabic({
	subsets: ["arabic"],
	variable: "--font-playpen",
});

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

const vazir = Vazirmatn({
	subsets: ["arabic"],
	variable: "--font-vazir",
});



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const currentUser = await getCurrentUser()

	let scrollbarThumb = "#EF4444";
	let scrollbarThumbHover = "#F87171";

	if (currentUser?.userRole === "ADMIN") {
		scrollbarThumb = "#3B82F6";
		scrollbarThumbHover = "#60A5FA";
	}

	if (currentUser?.userRole === "SELLER") {
		scrollbarThumb = "#A855F7";
		scrollbarThumbHover = "#C084FC";
	}

	return (
		<html
			lang="fa"
			style={{
				"--scrollbar-thumb": scrollbarThumb,
				"--scrollbar-thumb-hover": scrollbarThumbHover,
			} as React.CSSProperties}
		>
			<body
				className={`${playpen.variable} antialiased`}
			>
				<main>
					<Providers>
						{children}
					</Providers>
				</main>
			</body>
		</html>
	);
}
