import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn , Roboto , Playpen_Sans_Arabic} from "next/font/google";
import "./globals.css";
import Providers from "./providers";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playpen = Playpen_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-playpen",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`${playpen.variable} antialiased`}
      >
        <main>
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
